# Generated by Django 4.1.7 on 2023-06-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='dish',
            table='dish',
        ),
    ]
