# Generated by Django 4.1.7 on 2023-04-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('customers', '0003_rename_items_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='item',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.dish'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
