# Generated by Django 4.1.7 on 2023-04-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_dish_category_id_alter_item_dish_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='usernameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_field', models.CharField(error_messages={'unique': 'The username you entered is taken, please choose a new one.'}, max_length=200, unique=True)),
            ],
        ),
    ]
