# Generated by Django 4.1.7 on 2023-04-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_usernamemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usernameModel',
        ),
    ]
